spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/clickpicktest
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: taemin14215@gmail.com
    password: ??????
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000  # 3 * 60 * 1000 == 5분

  data:
    redis:
      host: localhost
      port: 6379




logging:
  level:
    org.hibernate.SQL: debug